name: Build and Publish Feed Resources

on:
  push:
    branches:
      - main

jobs:
  build-feeds:
    name: Update latest feed data from source repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Checkout Data Source Repo
        uses: actions/checkout@v2
        with:
          repository: smartcontractkit/reference-data-directory
          path: data-source
          token: ${{ secrets.GH_API_KEY }}
      # - name: Read Data Source
      #   run: cat data-source/package.json
      - name: Process Data
        run: yarn process
