name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install Dependencies
        run: npm i
      - name: Check Solidity Compilation
        run: npm run sol:compile
      - name: Check Solidity Solhint
        run: npm run lint-solc
      - name: Check Eslint
        run: npm run lint
      - name: Build
        run: npm run build
      # TODO: fix css files throwing 404 errors
      - name: Check Links
        run: npm run linkcheck